server {
    listen 443 ssl;
    ssl_certificate /root/.acme.sh/lebara.omatescomobile.com/lebara.omatescomobile.com.cer;
    ssl_certificate_key /root/.acme.sh/lebara.omatescomobile.com/lebara.omatescomobile.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Pass all decrypted traffic to SSLH for protocol inspection
    proxy_pass 127.0.0.1:4444;
}
